In [1]:
from os import rename

import pandas as pd
import time
import json
import importlib
import config
importlib.reload(config)

from config import US_TICKERS_FILE_01

In [73]:
with open(US_TICKERS_FILE_01, 'r') as f:
    tickers = json.load(f)

df_tickers = pd.DataFrame.from_dict(tickers, orient='index', columns=['Ticker', 'Start_Date', 'End_Date'])
df_tickers.index.name = 'ISIN'
df_tickers = df_tickers.reset_index()

print(df_tickers.shape)
print(df_tickers.head())

(28853, 4)
           ISIN Ticker  Start_Date    End_Date
0  US0970231058     BA  2018-01-01  2025-06-30
1  US0846701086   BRKA  2018-01-01  2025-06-30
2  US0846707026   BRKB  2018-01-01  2025-06-30
3  US12572Q1058    CME  2018-01-01  2025-06-30
4  US7081601061    JCP  2018-01-01  2021-01-06

In [85]:
df_tickers_us = df_tickers[df_tickers['ISIN'].str.startswith('US')]
print(df_tickers_us.shape)

(18328, 4)

In [74]:
df_tickers['Ticker'].nunique()

24272

In [75]:
df_tickers['ISIN'].nunique()

28853

In [5]:
PRICE_FILE_PATH = r"T:\CGATES\Alexandria\US_All_Universe_Returns_Daily_Sectors_2000_20240328.txt"
df_prices = pd.read_csv(PRICE_FILE_PATH, sep='\t')

In [31]:
df_prices['Ticker'].nunique()

3738

In [66]:
df_prices['Date'] = pd.to_datetime(df_prices['Date'])
dfp = df_prices[df_prices['Date']>='2018-01-01']
print(dfp.shape)
print(dfp['Ticker'].nunique())

(2358228, 6)
2084

In [67]:
dfp.head(50)

              Date Ticker      D0      D1  Return                  Sector
6798518 2018-01-02      A   67.60   69.32   2.54%  Information Technology
6798519 2018-01-02    AAL   52.99   52.34  -1.23%             Industrials
6798520 2018-01-02    AAN   39.47   39.67   0.51%  Consumer Discretionary
6798521 2018-01-02   AAOI   37.91   37.89  -0.05%  Information Technology
6798522 2018-01-02   AAON   36.95   37.60   1.76%             Industrials
6798523 2018-01-02    AAP  106.09  107.05   0.90%  Consumer Discretionary
6798524 2018-01-02   AAPL  172.26  172.23  -0.02%  Information Technology
6798525 2018-01-02    AAT   38.16   37.82  -0.89%              Financials
6798526 2018-01-02   AAWW   57.95   58.30   0.60%             Industrials
6798527 2018-01-02   AAXN   26.55   26.75   0.75%             Industrials
6798528 2018-01-02   ABAX   50.00   49.52  -0.96%             Health Care
6798529 2018-01-02   ABBV   98.41   99.95   1.56%             Health Care
6798530 2018-01-02    ABC   94.04   94.39   0.37%             Health Care
6798531 2018-01-02   ABCB   48.55   48.75   0.41%              Financials
6798532 2018-01-02    ABG   63.25   63.50   0.40%  Consumer Discretionary
6798533 2018-01-02    ABM   37.75   37.72  -0.08%             Industrials
6798534 2018-01-02   ABMD  192.49  195.82   1.73%             Health Care
6798535 2018-01-02    ABT   58.79   58.92   0.22%             Health Care
6798536 2018-01-02    ACC   40.99   40.31  -1.66%             Industrials
6798537 2018-01-02   ACET   10.62   10.92   2.82%             Health Care
6798538 2018-01-02   ACHC   33.81   33.43  -1.12%             Health Care
6798539 2018-01-02   ACIW   22.69   22.51  -0.79%  Information Technology
6798540 2018-01-02   ACLS   29.55   29.90   1.18%  Information Technology
6798541 2018-01-02    ACM   37.72   38.61   2.36%             Industrials
6798542 2018-01-02    ACN  153.84  154.55   0.46%             Health Care
6798543 2018-01-02   ACOR   22.65   21.90  -3.31%             Health Care
6798544 2018-01-02   ACXM   28.07   28.27   0.71%  Information Technology
6798545 2018-01-02   ADBE  177.70  181.04   1.88%  Information Technology
6798546 2018-01-02    ADC   51.43   51.34  -0.17%              Financials
6798547 2018-01-02    ADI   90.28   91.40   1.24%  Information Technology
6798548 2018-01-02    ADM   40.09   39.78  -0.77%        Consumer Staples
6798549 2018-01-02    ADP  115.99  117.25   1.09%             Industrials
6798550 2018-01-02    ADS  255.33  260.07   1.86%  Information Technology
6798551 2018-01-02   ADSK  107.12  109.38   2.11%  Information Technology
6798552 2018-01-02   ADTN   20.00   19.30  -3.50%  Information Technology
6798553 2018-01-02    AEE   58.39   58.09  -0.51%               Utilities
6798554 2018-01-02   AEGN   25.40   25.30  -0.39%             Industrials
6798555 2018-01-02   AEIS   69.41   68.92  -0.71%             Industrials
6798556 2018-01-02    AEL   30.82   30.81  -0.03%              Financials
6798557 2018-01-02    AEO   19.17   18.32  -4.43%  Consumer Discretionary
6798558 2018-01-02    AEP   72.41   71.80  -0.84%               Utilities
6798559 2018-01-02    AES   10.88   10.87  -0.09%               Utilities
6798560 2018-01-02    AET  180.69  181.80   0.61%             Health Care
6798561 2018-01-02   AFAM   56.00   56.25   0.45%             Health Care
6798562 2018-01-02    AFG  106.77  107.09   0.30%              Financials
6798563 2018-01-02    AFL   43.99   44.12   0.30%              Financials
6798564 2018-01-02   AGCO   71.63   72.02   0.54%             Industrials
6798565 2018-01-02    AGN  170.32  170.14  -0.11%             Health Care
6798566 2018-01-02   AGYS   12.47   12.53   0.48%  Information Technology
6798567 2018-01-02    AHH   15.53   15.40  -0.84%             Real Estate

In [76]:
x = dfp[['Ticker', 'Sector']].drop_duplicates()

df = df_tickers.merge(x, on='Ticker', how='inner')

print(x.shape)
print(df_tickers.shape)

print(df.shape)
print(df.head(50))

(2400, 2)
(28853, 4)
(3065, 5)
            ISIN Ticker  Start_Date    End_Date                      Sector
0   US0970231058     BA  2018-01-01  2025-06-30                 Industrials
1   US0846707026   BRKB  2018-01-01  2025-06-30                  Financials
2   US12572Q1058    CME  2018-01-01  2025-06-30                  Financials
3   US7081601061    JCP  2018-01-01  2021-01-06      Consumer Discretionary
4   US55616P1049      M  2018-01-01  2025-06-07      Consumer Discretionary
5   US5949181045   MSFT  2018-01-01  2025-06-30      Information Technology
6   US5894331017    MDP  2018-01-01  2021-12-03      Consumer Discretionary
7   US5894331017    MDP  2018-01-01  2021-12-03  Telecommunication Services
8   US5894331017    MDP  2018-01-01  2021-12-03      Communication Services
9   US8872281048   TIME  2018-01-01  2018-01-31      Consumer Discretionary
10  US1380981084    CMD  2018-01-01  2021-06-02                 Health Care
11  US2166484020    COO  2018-01-01  2025-06-17                 Health Care
12  US2521311074   DXCM  2018-01-01  2025-06-30                 Health Care
13  US28176E1082     EW  2018-01-01  2025-06-23                 Health Care
14  US67018T1051    NUS  2018-01-01  2025-06-25            Consumer Staples
15  IE00BGH1M568   PRGO  2018-01-01  2025-06-10            Consumer Staples
16  IE00BGH1M568   PRGO  2018-01-01  2025-06-10                 Health Care
17  US74838J1016   QDEL  2018-01-01  2022-08-01                 Health Care
18  US75901B1070   RGNX  2018-01-01  2025-06-20                 Health Care
19  US92532F1003   VRTX  2018-01-01  2025-06-23                 Health Care
20  US0010551028    AFL  2018-01-01  2025-06-30                  Financials
21  US03076C1062    AMP  2018-01-01  2025-06-23                  Financials
22  US14040H1059    COF  2018-01-01  2025-06-30                  Financials
23  US2925541029   ECPG  2018-01-01  2025-05-23                  Financials
24  US2922181043    EIG  2018-01-01  2025-06-25                  Financials
25  US3379307057    FBC  2018-01-01  2022-12-05                  Financials
26  US3189101062   FBNC  2018-01-01  2025-06-25                  Financials
27  US39304D1028   GDOT  2018-01-01  2025-06-20                  Financials
28  US4327481010    HTH  2018-01-01  2025-05-22                  Financials
29  US5404241086      L  2018-01-01  2025-06-20                  Financials
30  US7433151039    PGR  2018-01-01  2025-06-30                  Financials
31  US72346Q1040   PNFP  2018-01-01  2025-05-21                  Financials
32  US7593516047    RGA  2018-01-01  2025-06-18                  Financials
33  US78648T1007   SAFT  2018-01-01  2025-05-22                  Financials
34  US2036681086    CYH  2018-01-01  2025-06-09                 Health Care
35  US2333774071   DXPE  2018-01-01  2025-06-30                 Industrials
36  US60855R1005    MOH  2018-01-01  2025-06-09                 Health Care
37  US8982021060   TRUP  2018-01-01  2025-06-20                  Financials
38  US90337L1089   USPH  2018-01-01  2025-06-13                 Health Care
39  US0491642056   AAWW  2018-01-01  2023-03-17                 Industrials
40  US0079031078    AMD  2018-01-01  2025-06-30      Information Technology
41  US1295001044    CAL  2018-01-01  2025-06-30      Consumer Discretionary
42  US1717793095   CIEN  2018-01-01  2025-06-27      Information Technology
43  US1844961078    CLH  2018-01-01  2025-06-23                 Industrials
44  US20030N1019  CMCSA  2018-01-01  2025-06-30      Consumer Discretionary
45  US20030N1019  CMCSA  2018-01-01  2025-06-30  Telecommunication Services
46  US20030N1019  CMCSA  2018-01-01  2025-06-30      Communication Services
47  US2057683029    CRK  2018-01-01  2025-06-17                      Energy
48  US3989051095    GPI  2018-01-01  2025-06-24      Consumer Discretionary
49  US3647601083    GPS  2018-01-01  2025-06-11      Consumer Discretionary

In [77]:
print(df_tickers[df_tickers.duplicated(subset='Ticker', keep=False)].sort_values('Ticker').head(20))

               ISIN Ticker  Start_Date    End_Date
1771   US00846U1016      A  2018-01-03  2025-06-24
24988  CA04226J1084      A  2022-08-22  2022-10-04
16626  CA0120271089     AA  2020-01-28  2020-01-28
5021   US0138721065     AA  2018-01-13  2025-06-24
23369  CA33719F1099  AAA.P  2021-12-10  2025-06-24
11317  CA0534851088  AAA.P  2018-05-30  2021-08-27
23643  US38150K1034   AAAU  2022-01-19  2022-03-02
12213  US7154261025   AAAU  2018-08-15  2018-08-15
2183   US0003071083    AAC  2018-01-03  2021-07-24
22831  KYG330321061    AAC  2021-10-24  2023-11-01
18271  KY04316G1057   AACQ  2020-09-03  2021-06-25
17951  US04316G2049   AACQ  2020-07-17  2020-07-17
26017  KYG330331128   AACT  2023-04-26  2023-06-12
26369  KYG330331045   AACT  2023-08-21  2025-06-24
21736  US0240031056   AADI  2021-08-27  2021-09-14
21985  US00032Q1040   AADI  2021-09-20  2025-06-19
5476   CA00782P1080    AAL  2018-01-17  2020-04-14
1347   US02376R1023    AAL  2018-01-02  2025-06-30
27496  KYG1000R1193    AAM  2024-08-05  2024-09-11
27497  MHY009231058    AAM  2024-08-05  2025-05-29

In [78]:
dup_counts = df_tickers[df_tickers.duplicated(subset='Ticker', keep=False)].groupby('Ticker').size()
print(dup_counts.value_counts())

2    3207
3     552
4      80
5       7
Name: count, dtype: int64

In [79]:
dups = df_tickers[df_tickers.duplicated(subset='Ticker', keep=False)].sort_values(['Ticker','Start_Date'])
print(dups.head(20))

               ISIN Ticker  Start_Date    End_Date
1771   US00846U1016      A  2018-01-03  2025-06-24
24988  CA04226J1084      A  2022-08-22  2022-10-04
5021   US0138721065     AA  2018-01-13  2025-06-24
16626  CA0120271089     AA  2020-01-28  2020-01-28
11317  CA0534851088  AAA.P  2018-05-30  2021-08-27
23369  CA33719F1099  AAA.P  2021-12-10  2025-06-24
12213  US7154261025   AAAU  2018-08-15  2018-08-15
23643  US38150K1034   AAAU  2022-01-19  2022-03-02
2183   US0003071083    AAC  2018-01-03  2021-07-24
22831  KYG330321061    AAC  2021-10-24  2023-11-01
17951  US04316G2049   AACQ  2020-07-17  2020-07-17
18271  KY04316G1057   AACQ  2020-09-03  2021-06-25
26017  KYG330331128   AACT  2023-04-26  2023-06-12
26369  KYG330331045   AACT  2023-08-21  2025-06-24
21736  US0240031056   AADI  2021-08-27  2021-09-14
21985  US00032Q1040   AADI  2021-09-20  2025-06-19
1347   US02376R1023    AAL  2018-01-02  2025-06-30
5476   CA00782P1080    AAL  2018-01-17  2020-04-14
27496  KYG1000R1193    AAM  2024-08-05  2024-09-11
27497  MHY009231058    AAM  2024-08-05  2025-05-29

In [81]:
date_ranges = dfp.groupby('Ticker').agg(
    min_date=('Date', 'min'),
    max_date=('Date', 'max'),
    Sector=('Sector', 'first')
).reset_index()

print(date_ranges.shape)
print(date_ranges.head())

(2084, 4)
  Ticker   min_date   max_date                  Sector
0      A 2018-01-02 2024-03-28  Information Technology
1     AA 2019-01-02 2024-03-28               Materials
2    AAL 2018-01-02 2024-03-28             Industrials
3    AAN 2018-01-02 2024-01-31  Consumer Discretionary
4   AAOI 2018-01-02 2021-11-30  Information Technology

In [82]:
df = df_tickers.merge(date_ranges, on='Ticker', how='inner')

print(date_ranges.shape)
print(df_tickers.shape)

print(df.shape)
print(df.head(50))

(2084, 4)
(28853, 4)
(2655, 7)
            ISIN Ticker  Start_Date    End_Date   min_date   max_date  \
0   US0970231058     BA  2018-01-01  2025-06-30 2018-01-02 2024-03-28
1   US0846707026   BRKB  2018-01-01  2025-06-30 2018-01-02 2024-03-28
2   US12572Q1058    CME  2018-01-01  2025-06-30 2018-01-02 2024-03-28
3   US7081601061    JCP  2018-01-01  2021-01-06 2018-01-02 2020-04-30
4   US55616P1049      M  2018-01-01  2025-06-07 2018-01-02 2024-03-28
5   US5949181045   MSFT  2018-01-01  2025-06-30 2018-01-02 2024-03-28
6   US5894331017    MDP  2018-01-01  2021-12-03 2018-01-02 2021-11-30
7   US8872281048   TIME  2018-01-01  2018-01-31 2018-01-02 2018-01-29
8   US1380981084    CMD  2018-01-01  2021-06-02 2018-01-02 2021-05-28
9   US2166484020    COO  2018-01-01  2025-06-17 2018-01-02 2024-03-28
10  US2521311074   DXCM  2018-01-01  2025-06-30 2020-05-01 2024-03-28
11  US28176E1082     EW  2018-01-01  2025-06-23 2018-01-02 2024-03-28
12  US67018T1051    NUS  2018-01-01  2025-06-25 2018-01-02 2024-03-28
13  IE00BGH1M568   PRGO  2018-01-01  2025-06-10 2018-01-02 2024-03-28
14  US74838J1016   QDEL  2018-01-01  2022-08-01 2020-01-02 2024-03-28
15  US75901B1070   RGNX  2018-01-01  2025-06-20 2018-06-07 2024-03-28
16  US92532F1003   VRTX  2018-01-01  2025-06-23 2018-01-02 2024-03-28
17  US0010551028    AFL  2018-01-01  2025-06-30 2018-01-02 2024-03-28
18  US03076C1062    AMP  2018-01-01  2025-06-23 2018-01-02 2024-03-28
19  US14040H1059    COF  2018-01-01  2025-06-30 2018-01-02 2024-03-28
20  US2925541029   ECPG  2018-01-01  2025-05-23 2018-01-02 2024-03-28
21  US2922181043    EIG  2018-01-01  2025-06-25 2018-01-02 2024-03-28
22  US3379307057    FBC  2018-01-01  2022-12-05 2018-10-23 2022-11-29
23  US3189101062   FBNC  2018-01-01  2025-06-25 2021-01-04 2024-03-28
24  US39304D1028   GDOT  2018-01-01  2025-06-20 2018-01-02 2024-03-28
25  US4327481010    HTH  2018-01-01  2025-05-22 2021-01-04 2024-03-28
26  US5404241086      L  2018-01-01  2025-06-20 2018-01-02 2024-03-28
27  US7433151039    PGR  2018-01-01  2025-06-30 2018-01-02 2024-03-28
28  US72346Q1040   PNFP  2018-01-01  2025-05-21 2018-01-02 2024-03-28
29  US7593516047    RGA  2018-01-01  2025-06-18 2018-01-02 2024-03-28
30  US78648T1007   SAFT  2018-01-01  2025-05-22 2018-01-02 2024-03-28
31  US2036681086    CYH  2018-01-01  2025-06-09 2018-01-02 2024-01-31
32  US2333774071   DXPE  2018-01-01  2025-06-30 2018-01-02 2024-03-28
33  US60855R1005    MOH  2018-01-01  2025-06-09 2018-01-02 2024-03-28
34  US8982021060   TRUP  2018-01-01  2025-06-20 2020-01-02 2024-03-28
35  US90337L1089   USPH  2018-01-01  2025-06-13 2018-01-02 2024-03-28
36  US0491642056   AAWW  2018-01-01  2023-03-17 2018-01-02 2023-03-23
37  US0079031078    AMD  2018-01-01  2025-06-30 2018-01-02 2024-03-28
38  US1295001044    CAL  2018-01-01  2025-06-30 2018-01-02 2024-03-28
39  US1717793095   CIEN  2018-01-01  2025-06-27 2018-01-02 2024-03-28
40  US1844961078    CLH  2018-01-01  2025-06-23 2018-01-02 2024-03-28
41  US20030N1019  CMCSA  2018-01-01  2025-06-30 2018-01-02 2024-03-28
42  US2057683029    CRK  2018-01-01  2025-06-17 2023-04-03 2024-03-28
43  US3989051095    GPI  2018-01-01  2025-06-24 2018-01-02 2024-03-28
44  US3647601083    GPS  2018-01-01  2025-06-11 2018-01-02 2024-03-28
45  US5951121038     MU  2018-01-01  2025-06-30 2018-01-02 2024-03-28
46  US6516391066    NEM  2018-01-01  2025-06-30 2018-01-02 2024-03-28
47  US6936561009    PVH  2018-01-01  2025-06-30 2018-01-02 2024-03-28
48  US7237871071    PXD  2018-01-01  2024-05-03 2018-01-02 2024-03-28
49  US80874P1093   SGMS  2018-01-01  2025-06-25 2018-01-02 2022-03-30

                    Sector
0              Industrials
1               Financials
2               Financials
3   Consumer Discretionary
4   Consumer Discretionary
5   Information Technology
6   Consumer Discretionary
7   Consumer Discretionary
8              Health Care
9              Health Care
10             Health Care
11             Health Care
12        Consumer Staples
13        Consumer Staples
14             Health Care
15             Health Care
16             Health Care
17              Financials
18              Financials
19              Financials
20              Financials
21              Financials
22              Financials
23              Financials
24              Financials
25              Financials
26              Financials
27              Financials
28              Financials
29              Financials
30              Financials
31             Health Care
32             Industrials
33             Health Care
34              Financials
35             Health Care
36             Industrials
37  Information Technology
38  Consumer Discretionary
39  Information Technology
40             Industrials
41  Consumer Discretionary
42                  Energy
43  Consumer Discretionary
44  Consumer Discretionary
45  Information Technology
46               Materials
47  Consumer Discretionary
48                  Energy
49  Consumer Discretionary

In [83]:
dups = df_tickers[df_tickers.duplicated(subset='Ticker', keep=False)].sort_values(['Ticker','Start_Date'])
print(dups.head(20))

               ISIN Ticker  Start_Date    End_Date
1771   US00846U1016      A  2018-01-03  2025-06-24
24988  CA04226J1084      A  2022-08-22  2022-10-04
5021   US0138721065     AA  2018-01-13  2025-06-24
16626  CA0120271089     AA  2020-01-28  2020-01-28
11317  CA0534851088  AAA.P  2018-05-30  2021-08-27
23369  CA33719F1099  AAA.P  2021-12-10  2025-06-24
12213  US7154261025   AAAU  2018-08-15  2018-08-15
23643  US38150K1034   AAAU  2022-01-19  2022-03-02
2183   US0003071083    AAC  2018-01-03  2021-07-24
22831  KYG330321061    AAC  2021-10-24  2023-11-01
17951  US04316G2049   AACQ  2020-07-17  2020-07-17
18271  KY04316G1057   AACQ  2020-09-03  2021-06-25
26017  KYG330331128   AACT  2023-04-26  2023-06-12
26369  KYG330331045   AACT  2023-08-21  2025-06-24
21736  US0240031056   AADI  2021-08-27  2021-09-14
21985  US00032Q1040   AADI  2021-09-20  2025-06-19
1347   US02376R1023    AAL  2018-01-02  2025-06-30
5476   CA00782P1080    AAL  2018-01-17  2020-04-14
27496  KYG1000R1193    AAM  2024-08-05  2024-09-11
27497  MHY009231058    AAM  2024-08-05  2025-05-29

In [84]:
dups = df[df.duplicated(subset='Ticker', keep=False)].sort_values(['Ticker','Start_Date'])
print(dups.head(20))

              ISIN Ticker  Start_Date    End_Date   min_date   max_date  \
631   US00846U1016      A  2018-01-03  2025-06-24 2018-01-02 2024-03-28
2582  CA04226J1084      A  2022-08-22  2022-10-04 2018-01-02 2024-03-28
1555  US0138721065     AA  2018-01-13  2025-06-24 2019-01-02 2024-03-28
2292  CA0120271089     AA  2020-01-28  2020-01-28 2019-01-02 2024-03-28
481   US02376R1023    AAL  2018-01-02  2025-06-30 2018-01-02 2024-03-28
1627  CA00782P1080    AAL  2018-01-17  2020-04-14 2018-01-02 2024-03-28
1846  US0025353006    AAN  2018-01-22  2021-09-07 2018-01-02 2024-01-31
2252  CA0496AP1036    AAN  2019-12-17  2021-04-26 2018-01-02 2024-01-31
2495  US00258W1080    AAN  2021-10-07  2024-10-04 2018-01-02 2024-01-31
2510  CA0496AP2026    AAN  2021-10-27  2024-05-22 2018-01-02 2024-01-31
1806  US00751Y1064    AAP  2018-01-21  2025-06-30 2018-01-02 2024-03-28
2213  CA02078D1042    AAP  2019-07-11  2021-04-16 2018-01-02 2024-03-28
1378  US0240131047    AAT  2018-01-09  2025-06-04 2018-01-02 2024-03-28
2037  CA00208E2087    AAT  2018-05-05  2024-07-12 2018-01-02 2024-03-28
550   US03073E1055    ABC  2018-01-03  2023-08-30 2018-01-02 2023-09-29
2189  CA04517Y1034    ABC  2019-04-29  2019-04-29 2018-01-02 2023-09-29
2283  CA02452K1049    ABC  2020-01-16  2020-05-21 2018-01-02 2023-09-29
1544  US0009571003    ABM  2018-01-12  2025-06-17 2018-01-02 2024-03-28
2148  CA0468261031    ABM  2019-01-11  2025-02-10 2018-01-02 2024-03-28
1718  US0389231087    ABR  2018-01-19  2025-06-27 2023-07-03 2024-03-28

                      Sector
631   Information Technology
2582  Information Technology
1555               Materials
2292               Materials
481              Industrials
1627             Industrials
1846  Consumer Discretionary
2252  Consumer Discretionary
2495  Consumer Discretionary
2510  Consumer Discretionary
1806  Consumer Discretionary
2213  Consumer Discretionary
1378              Financials
2037              Financials
550              Health Care
2189             Health Care
2283             Health Care
1544             Industrials
2148             Industrials
1718              Financials

In [86]:
dup_counts = df_tickers_us[df_tickers_us.duplicated(subset='Ticker', keep=False)].groupby('Ticker').size()
print(dup_counts.value_counts())
print(f"Total tickers with duplicates: {len(dup_counts)}")

2    1417
3     101
4      10
Name: count, dtype: int64
Total tickers with duplicates: 1528

In [87]:
df_tickers_us = df_tickers_us.sort_values('End_Date', ascending=False).drop_duplicates(subset='Ticker', keep='first')

print(df_tickers_us.shape)
print(df_tickers_us.duplicated(subset='Ticker').sum())

(16679, 4)
0

In [88]:
df = df_tickers_us.merge(date_ranges, on='Ticker', how='inner')
print(df.shape)

(1932, 7)

In [ ]:
df.to_csv()

In [89]:
print(df['Sector'].value_counts())

Sector
Financials                    363
Consumer Discretionary        332
Industrials                   294
Information Technology        253
Health Care                   233
Energy                        107
Materials                     101
Consumer Staples               86
Utilities                      71
Real Estate                    56
Telecommunication Services     23
Communication Services         13
Name: count, dtype: int64

In [90]:
df['Sector'] = df['Sector'].replace('Telecommunication Services', 'Communication Services')
print(df['Sector'].value_counts())

Sector
Financials                363
Consumer Discretionary    332
Industrials               294
Information Technology    253
Health Care               233
Energy                    107
Materials                 101
Consumer Staples           86
Utilities                  71
Real Estate                56
Communication Services     36
Name: count, dtype: int64

In [92]:
df.shape

(1932, 7)

In [96]:
df.to_csv(r'P:\Personal\Birkbeck\MSc Project\git_msc_project_a\data\processed\us_tickers_1.csv', index=False)

In [41]:
myfilename =r"T:\CGATES\Alexandria\US_tickerlist2.csv"
df_sec = pd.read_csv(myfilename, sep=',', header=0)

print(df_sec.columns.tolist())
print(df_sec.head(2))
print(df_sec.shape)

['bb_tcm', 'Ticker', 'SECURITY_TYP', 'Unnamed: 3', 'Unnamed: 4', 'Sec_Type_Summary', 'Proceed', 'Count']
            bb_tcm Ticker               SECURITY_TYP  Unnamed: 3  Unnamed: 4  \
0  DKNGW US Equity  DKNGW  #N/A Field Not Applicable         NaN         NaN
1  ABBCL US Equity  ABBCL      #N/A Invalid Security         NaN         NaN

            Sec_Type_Summary Proceed  Count
0  #N/A Field Not Applicable      NO    1.0
1      #N/A Invalid Security      NO  285.0
(14900, 8)

In [9]:
df_tickers = df_tickers.merge(
    df_sec[['Ticker', 'SECURITY_TYP']].drop_duplicates(),
    on='Ticker',
    how='left')

In [23]:
df_sec.drop(columns=['Unnamed: 3','Unnamed: 4','Sec_Type_Summary','Proceed','Count'], inplace=True)

In [26]:
df_sec['SECURITY_TYP'].value_counts()

SECURITY_TYP
Common Stock                 10084
ETP                           1799
ADR                           1374
Closed-End Fund                607
REIT                           321
#N/A Invalid Security          285
Unit                           177
MLP                            111
Royalty Trst                    34
GDR                             28
Open-End Fund                   18
Ltd Part                        15
NY Reg Shrs                     10
Tracking Stk                    10
CDI                              6
Stapled Security                 3
Private Comp                     3
Misc.                            3
Receipt                          3
Preference                       2
Foreign Sh.                      1
Equity Index                     1
Dutch Cert                       1
#N/A Field Not Applicable        1
Equity WRT                       1
Index                            1
Savings Share                    1
Name: count, dtype: int64

In [28]:
df_sec.shape

(14900, 3)

In [16]:
import numpy as np

mask = (df_tickers['SECURITY_TYP'] == '#N/A Invalid Security') | (df_tickers['SECURITY_TYP'].isna())

invalid_isins = df_tickers.loc[mask, 'ISIN']
print(invalid_isins)
print(f"Count: {len(invalid_isins)}")

invalid_isins.to_clipboard()

1        US0846701086
2        US0846707026
7        CA0213611001
9        CA88581L1058
10       CA47215Q1046
             ...
29303    US33740F1104
29304    US80590A1051
29305    US71913T1034
29306    KYG4791J1224
29307    KYG2254C1050
Name: ISIN, Length: 12151, dtype: object
Count: 12151

In [11]:
df_tickers[['Ticker','ISIN']].to_clipboard()

In [13]:
df_tickers.shape

(29308, 6)

In [14]:
df_tickers.head(50)

,ISIN,Ticker,Start_Date,End_Date,Sector,SECURITY_TYP
0,US0970231058,BA,2018-01-01,2025-06-30,Industrials,Common Stock
1,US0846701086,BRKA,2018-01-01,2025-06-30,NaN,#N/A Invalid Security
2,US0846707026,BRKB,2018-01-01,2025-06-30,Financials,#N/A Invalid Security
3,US12572Q1058,CME,2018-01-01,2025-06-30,Financials,Common Stock
4,US7081601061,JCP,2018-01-01,2021-01-06,Consumer Discretionary,Common Stock
5,US55616P1049,M,2018-01-01,2025-06-07,Consumer Discretionary,Common Stock
6,US8123501061,SHLD,2018-01-01,2024-10-01,Consumer Discretionary,ETP
7,CA0213611001,ALA,2018-01-01,2025-06-27,NaN,NaN
8,US7168301049,PUGOY,2018-01-01,2021-01-20,NaN,ADR
9,CA88581L1058,IDK,2018-01-01,2019-11-22,NaN,NaN
10,CA47215Q1046,PJC.A,2018-01-01,2018-05-15,NaN,NaN
11,US20449X4016,CMPGY,2018-01-01,2025-06-30,NaN,ADR
12,SG9999012629,KEN,2018-01-01,2025-06-13,NaN,Common Stock
13,SG9999014708,ICP,2018-01-01,2018-01-01,NaN,Common Stock
14,US4650471083,IRLCY,2018-01-01,2018-05-24,NaN,ADR
15,IL0011015349,CEL,2018-01-01,2021-02-08,NaN,Common Stock
16,US8293471038,SIOLY,2018-01-01,2025-06-30,NaN,ADR
17,US8232181029,SHZNY,2018-01-01,2025-06-30,NaN,ADR
18,US2687801033,EONGY,2018-01-01,2025-06-16,NaN,ADR
19,US09523Q1013,APRN,2018-01-01,2019-12-17,NaN,Common Stock
20,US77543R1023,ROKU,2018-01-01,2025-06-23,NaN,Common Stock
21,US5949181045,MSFT,2018-01-01,2025-06-30,Information Technology,Common Stock
22,US05946K1016,BBVA,2018-01-01,2025-06-30,NaN,ADR
23,CA0641491075,BNS,2018-01-01,2025-06-30,NaN,Common Stock
24,CA5592224011,MG,2018-01-01,2025-06-30,NaN,Common Stock
25,CA78460T1057,SNC,2018-01-01,2025-06-27,Consumer Discretionary,Common Stock
26,CA28617B1013,EFL,2018-01-01,2022-11-30,NaN,Closed-End Fund
27,CA3197021064,FCC,2018-01-01,2021-12-06,NaN,NaN
28,CA34967D1015,FT,2018-01-01,2025-06-25,NaN,Closed-End Fund
29,CA7803571099,RNKLF,2018-01-01,2020-06-16,NaN,Common Stock
30,CA8239011031,S,2018-01-01,2025-06-11,Consumer Discretionary,Common Stock
31,CA8239011031,S,2018-01-01,2025-06-11,Telecommunication Services,Common Stock
32,US91912E1055,VALE,2018-01-01,2025-06-02,NaN,ADR
33,US5894331017,MDP,2018-01-01,2021-12-03,Consumer Discretionary,Common Stock
34,US5894331017,MDP,2018-01-01,2021-12-03,Telecommunication Services,Common Stock
35,US5894331017,MDP,2018-01-01,2021-12-03,Communication Services,Common Stock
36,US8872281048,TIME,2018-01-01,2018-01-31,Consumer Discretionary,ETP
37,US00900T1079,AIMT,2018-01-01,2020-10-15,NaN,Common Stock
38,US02155H1014,ALT,2018-01-01,2019-12-04,NaN,Common Stock
39,US03767D1081,APEN,2018-01-01,2023-04-03,NaN,Common Stock
40,US04624N1072,AST,2018-01-01,2019-03-08,NaN,Common Stock
41,US02081G2012,ATEC,2018-01-01,2025-06-17,NaN,Common Stock
42,US07725L1026,BGNE,2018-01-01,2025-06-30,NaN,ADR
43,US05070R1041,BOLD,2018-01-01,2025-06-02,NaN,Common Stock
44,US23257D1037,CBAY,2018-01-01,2024-03-22,NaN,Common Stock
45,US1376481016,CBIS,2018-01-01,2019-11-06,NaN,Common Stock
46,US15117P1021,CBMG,2018-01-01,2021-02-19,NaN,Common Stock
47,US1710774076,CDXC,2018-01-01,2025-06-27,NaN,Common Stock
48,US1380981084,CMD,2018-01-01,2021-06-02,Health Care,Common Stock
49,US2166484020,COO,2018-01-01,2025-06-17,Health Care,Common Stock

In [20]:
myfilename =r"T:\CGATES\Alexandria\US_tickerlist3.csv"
dfs2 = pd.read_csv(myfilename, sep=',', header=0)

print(dfs2.columns.tolist())
print(dfs2.head(2))

['Ticker', 'ISIN', 'TICKER_AND_EXCH_CODE', 'Unnamed: 3', 'Unnamed: 4']
  Ticker          ISIN       TICKER_AND_EXCH_CODE  Unnamed: 3 Unnamed: 4
0  HBANP  US4461504015  #N/A Field Not Applicable         NaN        NaN
1  CHSCP  US12542R2094  #N/A Field Not Applicable         NaN        NaN

In [22]:
dfs2.shape

(29308, 5)

In [35]:
myfilename =r"T:\CGATES\Alexandria\060726_bqnt_pull_1.txt"
df1 = pd.read_csv(myfilename, sep='\t', header=0)

print(df1.columns.tolist())
print(df1.head(2))
print(df1.shape)

['Unnamed: 0', 'bb_tcm', 'isin', 'start_date', 'end_date', 'average_last_price', 'average_volume', 'average_traded_volume', 'average_market_cap', 'ln_mktcap', 'ln_vol', 'ln_val', 'atv_M']
   Unnamed: 0              bb_tcm          isin  start_date    end_date  \
0           1  1573402D US Equity  US40053C1053  2018-01-18  2018-05-29
1           2  1624579D US Equity  US83408W1036  2018-01-15  2019-11-05

   average_last_price  average_volume  average_traded_volume  \
0            7.824286    1.906608e+06           1.488416e+07
1           35.719368    5.235073e+05           1.850647e+07

   average_market_cap  ln_mktcap     ln_vol     ln_val      atv_M
0           32.128372   3.500390  14.460837  16.515808  14.884161
1            1.389211   0.870963  13.168308  16.733631  18.506467
(2895, 13)

In [36]:
df1.shape

(2895, 13)

In [39]:
df1['isin'].nunique()

2895

In [40]:
missing = set(df1['isin']) - set(df_tickers['ISIN'])
print(f"{len(missing)} ISINs in B not found in A")
print(missing)

0 ISINs in B not found in A
set()

In [42]:
df1 = df1.rename(columns={'isin': 'ISIN'})

In [43]:
df_tickers = df_tickers.merge(
    df1.drop_duplicates(),
    on='ISIN',
    how='left')

In [44]:
print(df_tickers.shape)
print(df_tickers.isnull().sum())

(29308, 18)
ISIN                         0
Ticker                       2
Start_Date                   0
End_Date                     0
Sector                   25240
SECURITY_TYP             11983
Unnamed: 0               26191
bb_tcm                   26191
start_date               26191
end_date                 26191
average_last_price       26191
average_volume           26191
average_traded_volume    26191
average_market_cap       26198
ln_mktcap                26198
ln_vol                   26191
ln_val                   26191
atv_M                    26191
dtype: int64

In [59]:
df_tickers[df_tickers['SECURITY_TYP'].isna()]

,ISIN,Ticker,Start_Date,End_Date,Sector,SECURITY_TYP,Unnamed: 0,bb_tcm,start_date,end_date,average_last_price,average_volume,average_traded_volume,average_market_cap,ln_mktcap,ln_vol,ln_val,atv_M
7,CA0213611001,ALA,2018-01-01,2025-06-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,CA88581L1058,IDK,2018-01-01,2019-11-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,CA47215Q1046,PJC.A,2018-01-01,2018-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,CA3197021064,FCC,2018-01-01,2021-12-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
361,CA0977511017,BBD.A,2018-01-02,2025-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29303,US33740F1104,FBDC,2025-06-30,2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29304,US80590A1051,SCAG,2025-06-30,2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29305,US71913T1034,PXPCD,2025-06-30,2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29306,KYG4791J1224,INACU,2025-06-30,2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29307,KYG2254C1050,CCIIU,2025-06-30,2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
mask = ((df_tickers['SECURITY_TYP'].isna()) & ( df_tickers['bb_tcm'].isna()))
x = df_tickers.loc[mask]

In [61]:
x.to_csv(r'T:\CGATES\Alexandria\bb_tcm_finding_3.csv', index=False)

In [55]:
myfilename =r"T:\CGATES\Alexandria\bb_tcm_finding_2.csv"
df2 = pd.read_csv(myfilename, sep=',', header=0)
print(df2.columns)
print(df2.shape)

Index(['Unnamed: 0.1', 'Unnamed: 1', 'ISIN', 'Ticker', 'Start_Date',
       'End_Date', 'Sector', 'SECURITY_TYP', 'Unnamed: 0', 'bb_tcm',
       'ULT_PARENT_TICKER_EXCHANGE', 'INDUSTRY_SECTOR'],
      dtype='object')
(149, 12)

In [57]:
df2.drop(columns=['Unnamed: 0.1','Unnamed: 1','Unnamed: 0'], inplace=True)

In [58]:
df2[df2['']]

,ISIN,Ticker,Start_Date,End_Date,Sector,SECURITY_TYP,bb_tcm,ULT_PARENT_TICKER_EXCHANGE,INDUSTRY_SECTOR
0,US3456051099,FCEA,01/01/2018,11/12/2018,NaN,#N/A Invalid Security,FCE/A US,BN CN,Financial
1,US0549371070,BBT,02/01/2018,13/12/2019,Financials,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
2,US97382A2006,WIN,02/01/2018,15/03/2019,Consumer Staples,#N/A Invalid Security,B4O QT,UNIT US,Communications
3,US9426221019,WSOB,02/01/2018,06/10/2022,NaN,#N/A Invalid Security,WSO/B US,WSO US,"Consumer, Cyclical"
4,US46122T1025,XON,02/01/2018,04/02/2020,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
5,US3976242061,GEFB,02/01/2018,11/06/2025,NaN,#N/A Invalid Security,GEF/B US,GEF US,Industrial
6,US2246332066,CRDA,02/01/2018,30/06/2025,NaN,#N/A Invalid Security,CRD/A US,CRD/A US,Financial
7,US2246331076,CRDB,02/01/2018,30/06/2025,NaN,#N/A Invalid Security,CRD/B US,CRD/A US,Financial
8,US09248J1016,BNJ,02/01/2018,25/05/2018,NaN,#N/A Invalid Security,2211783D US,BLK US,Funds
9,US16948W1009,HGSH,03/01/2018,16/08/2021,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
10,US55939L3015,MNGA,03/01/2018,15/01/2018,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
11,US45824V2097,INSY,03/01/2018,24/01/2020,NaN,#N/A Invalid Security,INSYQ US,INSYQ US,"Consumer, Non-cyclical"
12,US09074M2026,BSTGD,03/01/2018,06/01/2025,NaN,#N/A Invalid Security,HRGN US,HRGN US,"Consumer, Non-cyclical"
13,US48343P2083,KALOD,03/01/2018,07/03/2019,NaN,#N/A Invalid Security,KALO US,KALO US,Technology
14,US22284P1057,CVTI,03/01/2018,03/06/2025,NaN,#N/A Invalid Security,CVLG US,CVLG US,Industrial
15,US60871R1005,TAPA,03/01/2018,27/06/2025,Financials,#N/A Invalid Security,TAP/A US,TAP US,"Consumer, Non-cyclical"
16,CA0679011084,ABX,04/01/2018,30/06/2025,Materials,#N/A Invalid Security,ABR PZ,ABX CN,Basic Materials
17,US9021041085,IIVI,04/01/2018,08/09/2022,Industrials,#N/A Invalid Security,2225789D US,COHR US,Industrial
18,US9021041085,IIVI,04/01/2018,08/09/2022,Information Technology,#N/A Invalid Security,2225789D US,COHR US,Industrial
19,CA4990531069,GUD,04/01/2018,17/06/2025,NaN,#N/A Invalid Security,KHTRF US,GUD CN,"Consumer, Non-cyclical"
20,US9682233054,JWB,04/01/2018,14/07/2023,NaN,#N/A Invalid Security,WLYB US,WLY US,"Consumer, Non-cyclical"
21,US2687851020,EPE,04/01/2018,27/08/2020,NaN,#N/A Invalid Security,EPEGQ US,EPEGQ US,Energy
22,CA87165R1082,SYN,04/01/2018,19/04/2018,NaN,#N/A Invalid Security,SYTHF US,SYN CN,Financial
23,US1156371007,BFA,04/01/2018,17/06/2025,NaN,#N/A Invalid Security,BF/A US,BF/B US,"Consumer, Non-cyclical"
24,US21036P2074,STZB,05/01/2018,10/11/2022,NaN,#N/A Invalid Security,STZ/B US,STZ US,"Consumer, Non-cyclical"
25,US3198501039,FBNK,05/01/2018,21/11/2019,NaN,#N/A Invalid Security,1752683D US,MTB US,Financial
26,US4461504015,HBANP,05/01/2018,05/01/2018,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
27,US78465V2043,SIFKY,06/01/2018,15/03/2021,NaN,#N/A Invalid Security,SRI LI,1559313D IN,Financial
28,US4195962000,HVTA,08/01/2018,23/06/2025,NaN,#N/A Invalid Security,HVT/A US,HVT US,"Consumer, Cyclical"
29,US3623931009,GTT,08/01/2018,30/12/2022,NaN,#N/A Invalid Security,GTTNQ US,GTTNQ US,Communications
30,US6708515001,OIBRC,09/01/2018,27/10/2021,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
31,CA36251Y1051,GTT,09/01/2018,03/06/2021,NaN,#N/A Invalid Security,2208790D US,NEM US,Basic Materials
32,US12542R2094,CHSCP,09/01/2018,02/04/2025,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
33,US6153943013,MOGB,09/01/2018,04/06/2025,NaN,#N/A Invalid Security,MOG/B US,MOG/A US,Industrial
34,US76882B2079,RMPL,10/01/2018,10/01/2018,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
35,US3893752051,GTNA,11/01/2018,30/06/2025,NaN,#N/A Invalid Security,GTN/A US,GTN US,Communications
36,CA3748252069,GEI,11/01/2018,17/06/2025,NaN,#N/A Invalid Security,GBNXF US,GEI CN,Energy
37,US87927Y2019,TIA,13/01/2018,05/07/2019,NaN,#N/A Invalid Security,TIAIY US,TIT IM,Communications
38,US45326V2025,INCPY,16/01/2018,28/03/2022,NaN,#N/A Invalid Security,2050290D US,INCH LN,"Consumer, Cyclical"
39,US55414P5044,MBVX,16/01/2018,24/05/2018,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
40,US58503T1060,MDLY,16/01/2018,08/07/2021,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
41,US2044098828,CIGC,17/01/2018,01/05/2025,NaN,#N/A Invalid Security,CIG/C US,CMIG4 BZ,Utilities
42,US55939L4005,MNGA,17/01/2018,20/02/2019,NaN,#N/A Invalid Security,NaN,#N/A Invalid Security,#N/A Invalid Security
43,CA3874371147,GRPU,17/01/2018,17/06/2025,NaN,#N/A Invalid Security,9234567D US,GRT-U CN,Financial
44,KYG747601105,RWGEU,18/01/2018,19/01/2018,NaN,#N/A Invalid Security,RWGE/U US,RWGE/U US,Diversified
45,US1616351078,CPKA,19/01/2018,19/07/2021,NaN,#N/A Invalid Security,WHLT US,WHLT US,Basic Materials
46,US3131481083,AGMA,21/01/2018,16/06/2025,NaN,#N/A Invalid Security,AGM/A US,AGM US,Financial
47,US86887P1012,SRNA,22/01/2018,20/01/2022,Information Technology,#N/A Invalid Security,2XS GR,BNC US,Financial
48,US21241B1008,CNTE,22/01/2018,22/07/2022,NaN,#N/A Invalid Security,1923625D US,AMR US,Energy
49,US46645Q1067,JRJR,22/01/2018,24/01/2022,NaN,#N/A Invalid Security,JRJRQ US,JRJRQ US,"Consumer, Cyclical"

In [98]:
df_tickers[df_tickers['ISIN']=='US36472T1097']

               ISIN Ticker  Start_Date    End_Date
16246  US36472T1097    GCI  2020-01-02  2025-06-24